### ISSUE TITLE
What does libnsm.so do ?

### ISSUE THREAD

**Issue by msnitish** [richardfan1126/nitro-enclave-python-demo#11]
In the **[attestation verifier](https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier)** docs, there is a mention of libnsm.so file.
I would like to know what is the purpose (functions it can perform) of this  _server/libnsm.so_ file. 
The  _server/libnsm.so_ file seems to be "_raw data_".
Is it editable file and how do we view the contents of it ?

**Comment by richardfan1126** [comment]
@msnitish 

The `libnsm.so` is actually compiled from this repository: https://github.com/donkersgoed/aws-nitro-enclaves-nsm-api/tree/main/nsm-lib

It's the library responsible to interact with the NSM (Nitro Security Module).

**Comment by msnitish** [comment]
@richardfan1126 
Thank you.
