### ISSUE TITLE
ACM for Nitro Enclaves

### ISSUE THREAD

**Issue by msnitish** [richardfan1126/nitro-enclave-python-demo#12]
In the [nitro-enclave-python-demo](https://github.com/richardfan1126/nitro-enclave-python-demo)/[attestation_verifier](https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier)/[client](https://github.com/richardfan1126/nitro-enclave-python-demo/tree/master/attestation_verifier/client)/client.py file, there seems to be no function which is validating the Attestation Document by checking the validity of certificate chain or which uses Nitro ACM.
***
1. Does the validation of Attestation document happen using the ACM for Nitro enclaves ?
2. If not, how exactly should the external service check the authenticity of the Enclave based on the received Attestation report ? (I am assuming that the after extracting the signed Attestation Document from the COSE_Sign1 file, we would have to validate the signature present in it after validating the certificate chain)

Thank you.

**Comment by richardfan1126** [comment]
Hi @msnitish 

The attestation process doesn't involve ACM.

The entire validation process is inside `attestation_verifier.py`

https://github.com/richardfan1126/nitro-enclave-python-demo/blob/c4f5dc2f3cb6c5bbd2f6a64f8d0d9ea9e029f6d1/attestation_verifier/secretstore/attestation_verifier.py#L13-L98

The process is based on the description which AWS provided: https://docs.aws.amazon.com/enclaves/latest/user/verify-root.html

**Comment by msnitish** [comment]
@richardfan1126 
Thank you. This made things clear regarding the validation process.
