### ISSUE TITLE
kmstool_enclave

### ISSUE THREAD

**Issue by jplock** [richardfan1126/nitro-enclave-python-demo#5]
Have you tried installing and using [kmstool_enclave](https://github.com/aws/aws-nitro-enclaves-sdk-c/tree/main/bin/kmstool-enclave) within the enclave, running vsock-proxy on the instance (which comes installed with the nitro-cli), then updating the client to conform to kmstool_enclave’s API of passing in credentials then issuing decrypt commands?

would the http proxy be required then to reach KMS? I don’t think it would. 

I’ve been trying to find the easiest way to set this up and found your project. Great work!

**Comment by richardfan1126** [comment]
Actually, I've contributed to kmstool_enclave repository on the [kmstool-enclave-cli](https://github.com/aws/aws-nitro-enclaves-sdk-c/tree/main/bin/kmstool-enclave-cli)

Check out this [branch](https://github.com/richardfan1126/nitro-enclave-python-demo/tree/kmstool-enclave-cli) to see how I make use of the kmstool

**Comment by jplock** [comment]
Very cool, thanks for the help!
